export const fmaPickerData = [
  { value: 'fry', label: 'Philip J. Fry', image: require('./img/fma/fry.png') },
  { value: 'leela', label: 'Turanga Leela', image: require('./img/fma/leela.png') },
  { value: 'bender', label: 'Bender Bending Rodriguez', image: require('./img/fma/bender.png') },
  { value: 'prof', label: 'Professor Hubert J. Farnsworth', image: require('./img/fma/prof.png') },
  { value: 'amy', label: 'Amy Wong', image: require('./img/fma/amy.png') },
  { value: 'hermes', label: 'Hermes Conrad', image: require('./img/fma/hermes.png') },
  { value: 'zoidberg', label: 'Dr. John A. Zoidberg', image: require('./img/fma/zoidberg.png') },
  { value: 'zapp', label: 'Zapp Brannigan', image: require('./img/fma/zapp.png') },
  { value: 'kif', label: 'Kif Kroker', image: require('./img/fma/kif.png') },
  { value: 'mom', label: 'Mom', image: require('./img/fma/mom.png') },
  { value: 'walt', label: 'Walt', image: require('./img/fma/walt.png') },
  { value: 'igner', label: 'Igner', image: require('./img/fma/igner.png') },
  { value: 'larry', label: 'Larry', image: require('./img/fma/larry.png') },
  { value: 'roberto', label: 'Roberto', image: require('./img/fma/roberto.png') },
  { value: 'nibbler', label: 'Nibbler', image: require('./img/fma/nibbler.png') },
  { value: 'scruffy', label: 'Scruffy', image: require('./img/fma/scruffy.png') },
  { value: 'url', label: 'URL', image: require('./img/fma/url.png') },
  { value: 'smitty', label: 'Smitty', image: require('./img/fma/smitty.png') },
  { value: 'elzar', label: 'Elzar', image: require('./img/fma/elzar.png') },
  { value: 'labarbara', label: 'LaBarbara Conrad', image: require('./img/fma/labarbara.png') },
  { value: 'hgblob', label: 'Horrible Gelatinous Blob', image: require('./img/fma/hgblob.png') },
  { value: 'calculon', label: 'Calculon', image: require('./img/fma/calculon.png') },
  { value: 'hedonismbot', label: 'Hedonismbot', image: require('./img/fma/hedonismbot.png') },
  { value: 'clamps', label: 'Clamps', image: require('./img/fma/clamps.png') },
  { value: 'donbot', label: 'Donbot', image: require('./img/fma/donbot.png') },
  { value: 'fanny', label: 'Fanny', image: require('./img/fma/fanny.png') },
  { value: 'lrrr', label: 'Lrrr', image: require('./img/fma/lrrr.png') },
  { value: 'ndnd', label: 'Ndnd', image: require('./img/fma/ndnd.png') },
  { value: 'santa', label: 'Robot Santa Claus', image: require('./img/fma/santa.png') },
  { value: 'flexo', label: 'Flexo', image: require('./img/fma/flexo.png') },
];
